export const image = [
    {
        "id":1,
        "logo":"https://upload.wikimedia.org/wikipedia/commons/b/b8/YouTube_Logo_2017.svg"

    },
    {
        "id":2,
        "logo":"https://www.freepnglogos.com/uploads/youtube-logo-hd-8.png"
    },
    {
        "id":3,
        "logo":"https://brandlogos.net/wp-content/uploads/2022/06/youtube_shorts-logo_brandlogos.net_vhmca-200x200.png"
    },
    {
        "id":4,
        "logo":"https://www.pngplay.com/wp-content/uploads/12/User-Avatar-Profile-Transparent-Free-PNG-Clip-Art.png"
    },
    {
        "id":5,
        "logo":"https://i.pinimg.com/736x/13/64/44/13644464403d975bc0648379573c03ee.jpg"
    },
    {
        "id":6,
        "logo":"https://creazilla-store.fra1.digitaloceanspaces.com/icons/3217758/feedback-icon-md.png"
    },
    {
        "id":7,
        "logo":"https://w7.pngwing.com/pngs/980/304/png-transparent-computer-icons-user-profile-avatar-heroes-silhouette-avatar.png"
    },
    {
        "id":8,
        "logo":"https://preview.redd.it/ive-found-a-youtube-error-related-to-the-searching-v0-c05hngz0uuea1.png?width=478&format=png&auto=webp&s=18279e1ac57f8b213e5a357309663b852bff7320"
    }
]